
CREATE TABLE users(
   user_id INT GENERATED ALWAYS AS IDENTITY,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   status INT,
   PRIMARY KEY(user_id)
);


CREATE TABLE boards(
   board_id INT GENERATED ALWAYS AS IDENTITY,
   user_id INT,
   board_name VARCHAR(255) NOT NULL,
   status INT,
   PRIMARY KEY(board_id),
   CONSTRAINT fk_user
      FOREIGN KEY(user_id) 
	  REFERENCES users(user_id)
);

CREATE TABLE lists(
   list_id INT GENERATED ALWAYS AS IDENTITY,
   board_id INT NOT NULL,
   name varchar(255) NOT NULL,
   counter INT DEFAULT 0, 
   status INT,
   PRIMARY KEY(list_id),
   CONSTRAINT fk_board
      FOREIGN KEY(board_id) 
	  REFERENCES boards(board_id)
);

CREATE TABLE cards(
   card_id INT GENERATED ALWAYS AS IDENTITY,
   list_id INT NOT NULL,
   name varchar(255) NOT NULL,
   description varchar(255),
   status INT,
   position INT GENERATED BY DEFAULT AS IDENTITY,
   PRIMARY KEY(card_id),
   CONSTRAINT fk_list
      FOREIGN KEY(list_id) 
	  REFERENCES lists(list_id)
);


delete from cards;
delete from lists;
delete from boards;
delete from users;
alter sequence boards_board_id_seq restart ;
alter sequence cards_position_seq  restart; 
alter sequence lists_list_id_seq restart;                
alter sequence users_user_id_seq restart; 
alter sequence cards_card_id_seq  restart;


